import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

interface SourceSnapshot {
  source: {
    name: string;
    url: string;
    license: string;
    retrieved: string;
  };
  names: string[];
}

const snapshotPath = path.resolve(
  'src/core/generation/naming/sourcePlaceNames.json',
);
const outputPath = path.resolve('src/core/generation/naming/sourceNameKeys.ts');

function comparisonKey(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/\p{Diacritic}/gu, '')
    .toLocaleLowerCase('en-US')
    .replace(/[^a-z]/g, '');
}

const snapshot = JSON.parse(
  await readFile(snapshotPath, 'utf8'),
) as SourceSnapshot;
const keys = [
  ...new Set(
    snapshot.names.flatMap((name) => [
      comparisonKey(name),
      ...name
        .split(/\s+/)
        .map(comparisonKey)
        .filter((part) => part.length >= 4),
    ]),
  ),
].sort();

const output = `// Generated by scripts/generateGeographicNameAssets.ts.
// Source: ${snapshot.source.name} (${snapshot.source.license})
// Retrieved: ${snapshot.source.retrieved}
export const SOURCE_PLACE_NAME_KEYS = [
${keys.map((key) => `  '${key}',`).join('\n')}
] as const;
`;

await writeFile(outputPath, output);
console.log(
  `Wrote ${keys.length} normalized source-name keys to ${path.relative(process.cwd(), outputPath)}.`,
);
